// export_string.h
// static version of text from Skins/export.dat
// used when that file is missing
// @(#) $Id: export_string.h,v 1.3 2012/01/13 18:28:29 macrae.i Exp $

static char * export_string =
    "<?xml version=\"1.0\"?>\r\n"
    "<?mso-application progid=\"Excel.Sheet\"?>\r\n"
    "<Workbook xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\"\r\n"
    " xmlns:o=\"urn:schemas-microsoft-com:office:office\"\r\n"
    " xmlns:x=\"urn:schemas-microsoft-com:office:excel\"\r\n"
    " xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\"\r\n"
    " xmlns:html=\"http://www.w3.org/TR/REC-html40\">\r\n"
    " <DocumentProperties xmlns=\"urn:schemas-microsoft-com:office:office\">\r\n"
    "  <Author>EMS MCDU Simulator</Author>\r\n"
    "  <LastAuthor>EMS MCDU Simulator</LastAuthor>\r\n"
    "  <Created>2009-03-23T15:34:17Z</Created>\r\n"
    "  <Company>EMS Technologies</Company>\r\n"
    "  <Version>11.9999</Version>\r\n"
    " </DocumentProperties>\r\n"
    " <ExcelWorkbook xmlns=\"urn:schemas-microsoft-com:office:excel\">\r\n"
    "  <WindowHeight>12465</WindowHeight>\r\n"
    "  <WindowWidth>18780</WindowWidth>\r\n"
    "  <WindowTopX>360</WindowTopX>\r\n"
    "  <WindowTopY>315</WindowTopY>\r\n"
    "  <ProtectStructure>False</ProtectStructure>\r\n"
    "  <ProtectWindows>False</ProtectWindows>\r\n"
    " </ExcelWorkbook>\r\n"
    " <Styles>\r\n"
    "  <Style ss:ID=\"Default\" ss:Name=\"Normal\">\r\n"
    "   <Alignment ss:Vertical=\"Bottom\"/>\r\n"
    "   <Borders/>\r\n"
    "   <Font/>\r\n"
    "   <Interior/>\r\n"
    "   <NumberFormat/>\r\n"
    "   <Protection/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s21\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s22\">\r\n"
    "   <Alignment ss:Horizontal=\"Left\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:Size=\"6\" ss:Color=\"#969696\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s23\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:Size=\"6\" ss:Color=\"#969696\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s24\">\r\n"
    "   <Font ss:Size=\"6\" ss:Color=\"#969696\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s25\">\r\n"
    "   <Font ss:Size=\"6\" ss:Color=\"#969696\"/>\r\n"
    "   <Interior/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s26\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s27\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Color=\"#FFFFFF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s28\">\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s30\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#FFFFFF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s31\">\r\n"
    "   <Font ss:Color=\"#FFFFFF\"/>\r\n"
    "   <Interior/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s32\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#00FFFF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s33\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#0000FF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s34\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#FFFFFF\"\r\n"
    "    ss:Bold=\"1\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s35\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font x:Family=\"Swiss\" ss:Color=\"#FF0000\"/>\r\n"
    "   <Interior ss:Color=\"#FFFF00\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s36\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:Color=\"#FFFFFF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s37\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Color=\"#00FF00\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s39\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:Size=\"8\" ss:Color=\"#808080\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s40\">\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#FFFFFF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s41\">\r\n"
    "   <Font ss:Color=\"#FFFFFF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s42\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#00CCFF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s43\">\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Color=\"#FFFFFF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s44\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#99CCFF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s45\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:Color=\"#FFFFFF\"/>\r\n"
    "   <Interior/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s46\">\r\n"
    "   <Interior/>\r\n"
    "  </Style>\r\n"
    "\r\n"
    "  <Style ss:ID=\"s_black\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#000000\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s_cyan\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#00FFFF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s_red\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#FF0000\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s_yellow\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#FFFF00\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s_green\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#008000\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s_magenta\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#FF00FF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s_amber\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#FFA500\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"s_white\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#FFFFFF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"b_black\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#000000\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"b_cyan\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#00FFFF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"b_red\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#FF0000\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"b_yellow\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#FFFF00\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"b_green\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#008000\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"b_magenta\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#FF00FF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"b_amber\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#FFA500\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    "  <Style ss:ID=\"b_white\">\r\n"
    "   <Alignment ss:Horizontal=\"Center\" ss:Vertical=\"Bottom\"/>\r\n"
    "   <Font ss:FontName=\"Courier New\" x:Family=\"Swiss\" ss:Size=\"8\" ss:Color=\"#FFFFFF\"/>\r\n"
    "   <Interior ss:Color=\"#000000\" ss:Pattern=\"Solid\"/>\r\n"
    "  </Style>\r\n"
    " </Styles>\r\n"
    " <Worksheet ss:Name=\"Sheet1\">\r\n"
    "  <Table ss:ExpandedColumnCount=\"30\" ss:ExpandedRowCount=\"17\" x:FullColumns=\"1\"\r\n"
    "   x:FullRows=\"1\">\r\n"
    "   <Column ss:AutoFitWidth=\"0\" ss:Width=\"11.25\" ss:Span=\"29\"/>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:MergeAcross=\"29\" ss:StyleID=\"s21\"><Data ss:Type=\"String\">Exported from MCDU Simulator</Data></Cell>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s22\"/>\r\n"
    "    <Cell ss:StyleID=\"s23\"/>\r\n"
    "    <Cell ss:StyleID=\"s23\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"><Data ss:Type=\"Number\">1</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"><Data ss:Type=\"Number\">4</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"><Data ss:Type=\"Number\">8</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"><Data ss:Type=\"Number\">12</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"><Data ss:Type=\"Number\">16</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"><Data ss:Type=\"Number\">20</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"><Data ss:Type=\"Number\">24</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s25\"/>\r\n"
    "    <Cell ss:StyleID=\"s23\"/>\r\n"
    "    <Cell ss:StyleID=\"s24\"/>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s22\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"><Data ss:Type=\"Number\">1</Data></Cell>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s22\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s35\"><Data ss:Type=\"String\">X</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s36\"><Data ss:Type=\"String\">1L</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s26\"><Data ss:Type=\"Number\">3</Data></Cell>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"/>\r\n"
    "    <Cell ss:StyleID=\"s36\"><Data ss:Type=\"String\">1R</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s35\"><Data ss:Type=\"String\">X</Data></Cell>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s39\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:StyleID=\"s39\"/>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s35\"><Data ss:Type=\"String\">X</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s36\"><Data ss:Type=\"String\">2L</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s26\"><Data ss:Type=\"Number\">5</Data></Cell>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"/>\r\n"
    "    <Cell ss:StyleID=\"s36\"><Data ss:Type=\"String\">2R</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s35\"><Data ss:Type=\"String\">X</Data></Cell>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s39\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:StyleID=\"s39\"><Data ss:Type=\"String\"> </Data></Cell>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s35\"><Data ss:Type=\"String\">X</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s36\"><Data ss:Type=\"String\">3L</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s26\"><Data ss:Type=\"Number\">7</Data></Cell>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"/>\r\n"
    "    <Cell ss:StyleID=\"s36\"><Data ss:Type=\"String\">3R</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s35\"><Data ss:Type=\"String\">X</Data></Cell>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s39\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:StyleID=\"s39\"/>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s35\"><Data ss:Type=\"String\">X</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s36\"><Data ss:Type=\"String\">4L</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s26\"><Data ss:Type=\"Number\">9</Data></Cell>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"/>\r\n"
    "    <Cell ss:StyleID=\"s36\"><Data ss:Type=\"String\">4R</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s35\"><Data ss:Type=\"String\">X</Data></Cell>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s39\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:StyleID=\"s39\"/>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s35\"><Data ss:Type=\"String\">X</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s36\"><Data ss:Type=\"String\">5L</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s26\"><Data ss:Type=\"Number\">11</Data></Cell>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"><Data ss:Type=\"String\">E</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s36\"><Data ss:Type=\"String\">5R</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s35\"><Data ss:Type=\"String\">X</Data></Cell>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s39\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"/>\r\n"
    "    <Cell ss:StyleID=\"s45\"/>\r\n"
    "    <Cell ss:StyleID=\"s39\"/>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s35\"><Data ss:Type=\"String\">X</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s36\"><Data ss:Type=\"String\">6L</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s26\"><Data ss:Type=\"Number\">13</Data></Cell>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"/>\r\n"
    "    <Cell ss:StyleID=\"s36\" ss:HRef=\"#'IFF TCAS'!A1\"><Data ss:Type=\"String\">6R</Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s35\"><Data ss:Type=\"String\">X</Data></Cell>\r\n"
    "   </Row>\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s22\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "$\r\n"
    "    <Cell ss:StyleID=\"s31\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "   </Row>\r\n"
    "<!--\r\n"
    "   <Row>\r\n"
    "    <Cell ss:StyleID=\"s22\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"/>\r\n"
    "    <Cell ss:Index=\"28\" ss:StyleID=\"s46\"/>\r\n"
    "    <Cell ss:StyleID=\"s26\"><Data ss:Type=\"String\"> </Data></Cell>\r\n"
    "    <Cell ss:StyleID=\"s22\"/>\r\n"
    "   </Row>\r\n"
    "-->\r\n"
    "  </Table>\r\n"
    "  <WorksheetOptions xmlns=\"urn:schemas-microsoft-com:office:excel\">\r\n"
    "   <Selected/>\r\n"
    "   <Panes>\r\n"
    "    <Pane>\r\n"
    "     <Number>3</Number>\r\n"
    "     <RangeSelection>R1C1:R17C30</RangeSelection>\r\n"
    "    </Pane>\r\n"
    "   </Panes>\r\n"
    "   <ProtectObjects>False</ProtectObjects>\r\n"
    "   <ProtectScenarios>False</ProtectScenarios>\r\n"
    "  </WorksheetOptions>\r\n"
    " </Worksheet>\r\n"
    " <!--\r\n"
    " <Worksheet ss:Name=\"Sheet2\">\r\n"
    "  <WorksheetOptions xmlns=\"urn:schemas-microsoft-com:office:excel\">\r\n"
    "   <ProtectObjects>False</ProtectObjects>\r\n"
    "   <ProtectScenarios>False</ProtectScenarios>\r\n"
    "  </WorksheetOptions>\r\n"
    " </Worksheet>\r\n"
    " <Worksheet ss:Name=\"Sheet3\">\r\n"
    "  <WorksheetOptions xmlns=\"urn:schemas-microsoft-com:office:excel\">\r\n"
    "   <ProtectObjects>False</ProtectObjects>\r\n"
    "   <ProtectScenarios>False</ProtectScenarios>\r\n"
    "  </WorksheetOptions>\r\n"
    " </Worksheet> -->\r\n"
    "</Workbook>\r\n";
