# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.2 (http://bakefile.sourceforge.net)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# C++ compiler
CXX := g++

# C compiler
CPP := gcc



# Standard flags for C++
CXXFLAGS :=

# Standard preprocessor flags (common for CC and CXX)
CPPFLAGS := -O0 -g3 -D _SIMULATOR_

# Standard linker flags
LDFLAGS :=

# Location and arguments of wx-config script
#WX_CONFIG := /usr/lib/wx/config/base-unicode-release-2.8
#WX_CONFIG := /usr/lib/wx/config/gtk2-unicode-debug-2.8
#WX_CONFIG := /usr/lib/wx/config/base-unicode-debug-2.8
WX_CONFIG := /usr/lib/wx/config/gtk2-unicode-release-2.8

# C++ flags to use with wxWidgets code
WX_CXXFLAGS := `$(WX_CONFIG) --cxxflags`



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CPPDEPS = -MT$@ -MF`echo $@ | sed -e 's,\.o$$,.d,'` -MD
MCDUSIM__CXXFLAGS =  -I.  -I/usr/local/include/wx-2.8 -I/usr/include/netinet -I./DDC/Linux/Include $(WX_CXXFLAGS) $(CPPFLAGS) $(CXXFLAGS)

#REM_RANGER_SIM___OBJECTS =  \
#	RemRangerSim.o \
#    remoteinspector.o \
#	cradleDlg.o

#REM_RANGER_SIM___C_OBJECTS =  \
#	event.o \
#    remoteApp.o \
#	cradleApp.o

PNG_OBJECTS =  \
	$(OBJS)\mcdusim.o \
	$(OBJS)\termScreen.o \
	$(OBJS)\transportTcp.o \
	$(OBJS)\transport.o \
	$(OBJS)\prot_739A.o \
	$(OBJS)\transportDDC.o \
	$(OBJS)\CConfDlg.o \
	$(OBJS)\pythonInt.o



CPP_INCLUDE = -I.

### Conditionally set variables: ###



### Targets: ###

all: mcdusim

install: all

uninstall:

clean:
	rm -f ./*.o
	rm -f ./*.d
	rm -f mcdusim

mcdusim: $(PNG_OBJECTS)
	$(CXX) -o $@ $(PNG_OBJECTS) $(LDFLAGS) -ldd42992 -lpthread  `$(WX_CONFIG) --libs xrc,html,adv,core,xml,base`

$(OBJS)\mcdusim.o: ./mcdusim.cpp ./mcdusim.h
	@$(CXX) -c -o $@ $(MCDUSIM__CXXFLAGS) $(CPPDEPS) $<
#	@$(CXX) -c -o $@ $(PNG_CXXFLAGS) $(CPPDEPS) -Wno-deprecated-declarations -Wno-deprecated $<

$(OBJS)\termScreen.o: ./termScreen.cpp ./termScreen.h
	@$(CXX) -c -o $@ $(MCDUSIM__CXXFLAGS) $(CPPDEPS) $<

$(OBJS)\transportTcp.o: ./transportTcp.cpp ./transportTcp.h ./transport.h
	@$(CXX) -c -o $@ $(MCDUSIM__CXXFLAGS) $(CPPDEPS) $<

$(OBJS)\transport.o: ./transport.cpp ./transport.h
	@$(CXX) -c -o $@ $(MCDUSIM__CXXFLAGS) $(CPPDEPS) $<

$(OBJS)\prot_739A.o: ./prot_739A.cpp ./prot_739A.h
	@$(CXX) -c -o $@ $(MCDUSIM__CXXFLAGS) $(CPPDEPS) $<

$(OBJS)\transportDDC.o: ./transportDDC.cpp ./transportDDC.h ./transport.h
	@$(CXX) -c -o $@ $(MCDUSIM__CXXFLAGS) $(CPPDEPS) $<

$(OBJS)\CConfDlg.o: ./CConfDlg.cpp ./CConfDlg.h
	@$(CXX) -c -o $@ $(MCDUSIM__CXXFLAGS) $(CPPDEPS) $<

$(OBJS)\pythonInt.o: ./pythonInt.cpp ./pythonInt.h
	@$(CXX) -c -o $@ $(MCDUSIM__CXXFLAGS) $(CPPDEPS) $<

.PHONY: all install uninstall clean


# Dependencies tracking:
-include ./*.d
